/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *

 */
@isTest
private class DemoClass {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        //only half of  the comments are removed in this git file
    }
}
